title: Bit치cora del capit치n
email: j2arcidiacono@outlook.com
description: >- 
  Un blog en el que pruebo cosas de electr칩nica y programaci칩n.
baseurl: "/" 
domain: mokocchi.github.io
url: "https://mokocchi.github.io/" 
twitter_username: mokonahyuu
github_username:  mokocchi
paginate: 5
paginate_path: "/page:num/"

theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
  - jekyll-paginate